//================= Network Configration =======================//
const URIS = {
    // DEVELOPMENT: 'http://10.100.4.13:4181/ramky/',
    // DEVELOPMENT: 'http://35.244.6.49:4181/', //old server url
    // DEVELOPMENT:'https://iris.resustainability.com/',
    DEVELOPMENT: 'https://deviris.resustainability.com/ramky/', // dev instance
    // DEVELOPMENT:'https://uatiris.resustainability.com/ramky/',  // server instance
    PRODUCTION: '',
    STAGING: '',
};
const HTTP_CODES = {
    SUCCESS: 200,
    UNAUTHORIZED: 401,
    VALIDATION: 422,
    SERVER_ERROR: 500,
};
// eslint-disable-next-line camelcase
const URI_METHODs = {
    LOGIN: 'login/',
    REGISTRATION: 'user/registration',
    CHANGEPASSWORD: 'Account-Info/Update-Password/',
    FORGOT_EMAIL: 'Account-Info/Forgot-Password?',
    OTP_VERIFY: 'Account-Info/Check-OTP?',
    CREATE_NEW_PASSWORD: 'Account-Info/Reset-Password?',
    RESEND_OTP: 'Account-Info/Resend-OTP?',
    HELPCENTER_CONTACTUS: 'Account-Info/Get-Notification-Helpline-Number',
    HELPCENTER_FAQ: 'Account-Info/Get-All-Notification-FAQ',
    // *********************** Dashboard *****************************
    // DASHBOARD_COLLECTION: 'mswSiteOperator/getMswCollect',
    // DASHBOARD_PROCESSING: 'mswSiteOperator/getMswSorting',
    // DASHBOARD_DISTRIBUTION: 'mswSiteOperator/getMswDistribute',
    // eslint-disable-next-line camelcase
    // COllECTION_TREND_VALUE: 'mswSiteOperator/getCollectionTrend?',
    // PROCESSING_TREND_VALUE: 'mswSiteOperator/getProcessingTrend?',
    // DISTRIBUTION_COMPOST_OUTFLOW: 'mswSiteOperator/getMswDistributeCompostOutflow',
    // DISTRIBUTION_RDF_OUTFLOW: 'mswSiteOperator/getMswDistributeRdf?',
    // DISTRIBUTION_RECYCLABLE_OUTFLOW: 'mswSiteOperator/getMswDistributeRecyclables?',
    // DISTRIBUTION_INERTS_OUTFLOW: 'mswSiteOperator/getMswDistributeInerts?',
    // DASHBOARD_COMBINE_DATA: 'mswDashboard/getCombineDataMswDashboard?',

    DASHBOARD_COLLECTION: 'mso/mso2/gmc',
    DASHBOARD_PROCESSING: 'mso/mso4/gms',
    DASHBOARD_DISTRIBUTION: 'mso/mso6/gmd',
    // // eslint-disable-next-line camelcase
    COllECTION_TREND_VALUE: 'mso/mso7/gct',
    PROCESSING_TREND_VALUE: 'mso/mso8/gpt',
    DISTRIBUTION_COMPOST_OUTFLOW: 'mso/mso9/gmdco',
    DISTRIBUTION_RDF_OUTFLOW: 'mso/mso10/gmdrdf',
    DISTRIBUTION_RECYCLABLE_OUTFLOW: 'mso/mso12/gmdrs',
    DISTRIBUTION_INERTS_OUTFLOW: 'mso/mso11/gmdi',
    // DASHBOARD_COMBINE_DATA: 'mswDashboard/getCombineDataMswDashboard?',
    // *********************** Dashboard *****************************
    //******************************DadshboardC&tuser**************** 
    // CT_DASHBOARD_POST_COLLECTION: 'Msw-Siteoperator-C&T/saveMswCollect',
    // CT_DASHBOARD_GET_COLLECTION: 'Msw-Siteoperator-C&T/getMswCollect',
    // CT_DASHBOARD_GET_PROCESSING: 'Msw-Siteoperator-C&T/getMswSorting',
    // CT_DASHBOARD_GET_DISTRIBUTE: 'Msw-Siteoperator-C&T/getMswDistribute',
    // CT_DASHBOARD_COLLECTION_TREND_VALUE: 'Msw-Siteoperator-C&T/getCollectionTrend/?',
    // CT_DASHBOARD_PROCESSING_TREND_VALUE: 'Msw-Siteoperator-C&T/getProcessingTrend/?',
    // CT_DISTRIBUTION_COMPOST_OUTFLOW: 'Msw-Siteoperator-C&T/getMswDistributeCompostOutflow/?',
    // CT_DISTRIBUTION_RDF_OUTFLOW: 'Msw-Siteoperator-C&T/getMswDistributeRdf/?',
    // CT_DISTRIBUTION_RECYCLABLE_OUTFLOW: 'Msw-Siteoperator-C&T/getMswDistributeRecyclables/?',
    // CT_DISTRIBUTION_INERTS_OUTFLOW: 'Msw-Siteoperator-C&T/getMswDistributeInerts/?',
    // CT_DASHBOARD_POST_HISTORY: 'Msw-Siteoperator-C&T/Get-Msw-Collect-History?',
    // CD_DASHBOARD_HISTORY: 'mswSiteOperator/Get-Msw-SortingDistribute-History?',
    // CT_PRODUCT_CATALOGUE: 'Msw-Siteoperator-C&T/Get-Msw-Product-Catalogue-C&T?',
    // CD_PRODUCT_CATALOGUE: 'mswSiteOperator/Get-Msw-Product-Catalogue-P&D?',

    CT_DASHBOARD_POST_COLLECTION: 'msct/msct1/smc',
    CT_DASHBOARD_GET_COLLECTION: 'msct/msct2/gmc',
    CT_DASHBOARD_GET_PROCESSING: 'msct/msct3/gms',
    CT_DASHBOARD_GET_DISTRIBUTE: 'msct/msct4/gmd',
    CT_DASHBOARD_COLLECTION_TREND_VALUE: 'msct/msct5/gct',
    CT_DASHBOARD_PROCESSING_TREND_VALUE: 'msct/msct6/gpt',
    CT_DISTRIBUTION_COMPOST_OUTFLOW: 'msct/msct7/gmdco',
    CT_DISTRIBUTION_RDF_OUTFLOW: 'msct/msct8/gmdrdf',
    CT_DISTRIBUTION_RECYCLABLE_OUTFLOW: 'msct/msct10/gmdrs',
    CT_DISTRIBUTION_INERTS_OUTFLOW: 'msct/msct9/gmdi',
    CT_DASHBOARD_POST_HISTORY: 'msct/msct11/gmch',
    CD_DASHBOARD_HISTORY: 'mso/mso13/gmsdh',
    CT_PRODUCT_CATALOGUE: 'msct/msct12/gmpcpd',
    CD_PRODUCT_CATALOGUE: 'mso/mso14/gmpcpd?',
    // ************************* Sitehead  ***************************
    SITEHEAD_WASTECOLLECTED: 'mswSiteHead/Get-Waste-Summary?',
    SITEHEAD_WTEPROCESSED: 'mswSiteHead/getSiteHeadWteProcessed?',
    SITEHEAD_COLLECTION_TREND: 'mswSiteHead/getSiteHeadCollectionTrend?',
    SITEHEAD_PROCESSING_TREND: 'mswSiteHead/getSiteHeadProcessingTrend?',
    SITEHEAD_WTE_TREND: 'mswSiteHead/getSiteHeadWteTrend?',
    SITEHEAD_DISTRIBUTION_COMPOST_TREND: 'mswSiteHead/getMswDistributeCompostOutflow?',
    SITEHEAD_DISTRIBUTION_RDF_TREND: 'mswSiteHead/getMswDistributeRdf?',
    SITEHEAD_DISTRIBUTION_RECYCLABLE_TREND: 'mswSiteHead/getMswDistributeRecyclables?',
    SITEHEAD_DISTRIBUTION_INERTS_TREND: 'mswSiteHead/getMswDistributeInerts?',
    SITEHEAD_HISTORY: 'mswSiteHead/Get-Msw-History?',
    MSW_SITEHEAD_COLLECTION: 'mswSiteHead/Get-Side-Navbar-Collected-Waste?',
    MSW_SITEHEAD_PROCESSED: 'mswSiteHead/Get-Side-Navbar-Processed-Waste?',
    MSW_SITEHEAD_DISTRIBUTE: 'mswSiteHead/Get-Side-Navbar-Distribute-Waste?',
    MSW_SITEHEAD_WTE: 'mswSiteHead/Get-Side-Navbar-Wte-Waste?',

    // SITEHEAD_WASTECOLLECTED:'msh/msh1/gws',
    // SITEHEAD_WTEPROCESSED: 'msh/msh4/gshwp',
    // SITEHEAD_COLLECTION_TREND: 'msh/msh2/gshct',
    // SITEHEAD_PROCESSING_TREND: 'msh/msh3/gshpt',
    // SITEHEAD_WTE_TREND: 'msh/msh5/gshwt',
    // SITEHEAD_DISTRIBUTION_COMPOST_TREND: 'msh/msh6/gmdco',
    // SITEHEAD_DISTRIBUTION_RDF_TREND: 'msh/msh7/gmdrdf',
    // SITEHEAD_DISTRIBUTION_RECYCLABLE_TREND: 'msh/msh9/gmdrs',
    // SITEHEAD_DISTRIBUTION_INERTS_TREND: 'msh/msh8/gmdi',
    // SITEHEAD_HISTORY: 'msh/msh14/gmh',
    // MSW_SITEHEAD_COLLECTION: 'msh/msh10/gsncw',
    // MSW_SITEHEAD_PROCESSED: 'msh/msh11/gsnpw',
    // MSW_SITEHEAD_DISTRIBUTE: 'msh/msh12/gsndw',
    // MSW_SITEHEAD_WTE: 'msh/msh13/gsnww',
    // ************************* Businesshead  ***************************
    BUSINESS_WTEPROCESSED: 'mswBusinessHead/getBusinessHeadWteProcessed?',
    BUSINESS_COMBINEDATA: 'mswBusinessHead/getCombineDataBusinessHead?',
    BUSINESS_COLLECTION_TREND: 'mswBusinessHead/getBusinessHeadCollectionTrend?',
    BUSINESS_PROCESSING_TREND: 'mswBusinessHead/getBusinessHeadProcessingTrend?',
    BUSINESS_WTE_TREND: 'mswBusinessHead/getBusinessHeadWteTrend?',
    BUSINESS_DISTRIBUTION_COMPOST_TREND: 'mswBusinessHead/getMswDistributeCompostOutflow?',
    BUSINESS_DISTRIBUTION_RDF_TREND: 'mswBusinessHead/getMswDistributeRdf?',
    BUSINESS_DISTRIBUTION_RECYCLABLE_TREND: 'mswBusinessHead/getMswDistributeRecyclables?',
    BUSINESS_DISTRIBUTION_INERTS_TREND: 'mswBusinessHead/getMswDistributeInerts?',
    BUSINESS_RDF_VALUE: 'mswBusinessHead/getMswSbuRdf',
    BUSINESS_ENERGY_VALUE: 'mswBusinessHead/getMswSbuEnergy',
    BUSINESS_ASH_VALUE: 'mswBusinessHead/getMswSbuAsh',
    SBUHEAD_HISTORY: 'mswBusinessHead/Get-Msw-History?',
    SBUHEAD_COLLECTED: 'mswBusinessHead/Get-Side-Navbar-Collected-Waste',
    SBUHEAD_PROCESSED: 'mswBusinessHead/Get-Side-Navbar-Processed-Waste',
    SBUHEAD_DISTRIBUTE: 'mswBusinessHead/Get-Side-Navbar-Distribute-Waste',
    SBUHEAD_WTE: 'mswBusinessHead/Get-Side-Navbar-Wte-Waste',

    // BUSINESS_WTEPROCESSED: 'mbh/mbh11/gbhwp',
    // BUSINESS_COMBINEDATA: 'mbh/mbh1/gcdbh',
    // BUSINESS_COLLECTION_TREND: 'mbh/mbh2/gbhct',
    // BUSINESS_PROCESSING_TREND: 'mbh/mbh3/gbhpt',
    // BUSINESS_WTE_TREND: '/mbh/mbh12/gbhwt',
    // BUSINESS_DISTRIBUTION_COMPOST_TREND: 'mbh/mbh4/gmdco',
    // BUSINESS_DISTRIBUTION_RDF_TREND: 'mbh/mbh5/gmdrdf',
    // BUSINESS_DISTRIBUTION_RECYCLABLE_TREND: 'mbh/mbh7/gmdrs',
    // BUSINESS_DISTRIBUTION_INERTS_TREND: 'mbh/mbh6/gmdi',
    // BUSINESS_RDF_VALUE: 'mbh/mbh13/gmsrdf',
    // BUSINESS_ENERGY_VALUE: 'mbh/mbh14/gmse',
    // BUSINESS_ASH_VALUE: 'mbh/mbh15/gmsa',
    // SBUHEAD_HISTORY: 'mbh/mbh20/gmw',
    // SBUHEAD_COLLECTED: 'mbh/mbh16/gsncw',
    // SBUHEAD_PROCESSED: 'mbh/mbh17/gsnpw',
    // SBUHEAD_DISTRIBUTE: 'mbh/mbh18/gsndw',
    // SBUHEAD_WTE: 'mbh/mbh19/gsnww',
    // **************************Footer*************************
    COLLECT_FOOTER: 'mswSiteOperator/saveMswCollect',
    PROCESS_FOOTER: 'mswSiteOperator/saveMswSorting',
    WTE_USERFOOTER: 'mswWteUser/saveMswWteUser',
    DISTRIBUTE_FOOTER: 'mswSiteOperator/saveMswDistribute',

    // COLLECT_FOOTER: 'mso/mso1/smc',
    // PROCESS_FOOTER: 'mso/mso3/sms',
    // WTE_USERFOOTER: 'mwu/mwu1/smwu',
    // DISTRIBUTE_FOOTER: 'mso/mso5/smd',
    // **************************Footer*************************
    // ************************ WTE user***************************
    WTE_ENERGY_GENERATED: 'mswWteUser/getMswWteUserEnergy',
    RDF_PROCESSED: 'mswWteUser/getMswWteUserRdf',
    ASH_GENERATED: 'mswWteUser/getMswWteUserAsh',
    RDF_TREND: 'mswWteUser/getMswWteRdfTrend?',
    ENERGY_TREND: 'mswWteUser/getMswWteEnergyTrend?',
    ASH_TREND: 'mswWteUser/getMswWteAshTrend?',
    WTE_HISTORY: 'mswWteUser/Get-Msw-Wte-History?',

    // WTE_ENERGY_GENERATED: 'mwu/mwu3/gmwue',
    // RDF_PROCESSED: 'mwu/mwu2/gmwur',
    // ASH_GENERATED: 'mwu/mwu4/gmwuash',
    // RDF_TREND: 'mwu/mwu5/gmwrt',
    // ENERGY_TREND: 'mwu/mwu6/gmwet',
    // ASH_TREND: 'mwu/mwu7/gmwat',
    // WTE_HISTORY: 'mwu/mwu8/gmwh',
    // ************************ BMW user***************************
    COLLECT_DASHBOARDBMW: 'Bmw-Site-Operator/Get-Bmw-Collect',
    SORTING_DASHBOARDBMW: 'Bmw-Site-Operator/Get-Bmw-Sorting',
    RECYCLABLE_DASHBOARDBMW: 'Bmw-Site-Operator/Get-Bmw-Distribute',
    BMW_SUMMARY: 'Bmw-Site-Operator/Get-Bmw-Summary?',
    BMW_COLLECTIONTREND: 'Bmw-Site-Operator/Get-Collection-Trend?',
    BMW_PROCESSINGTREND: 'Bmw-Site-Operator/Get-Processing-Trend?',
    BMW_RECYCLABLETREND: 'Bmw-Site-Operator/Get-Distribute-Trend?',
    BMW_RECYCLABLES: 'Bmw-Site-Operator/Get-Recyclable-Data?',
    BMW_FOOTERCOLLECT: 'Bmw-Site-Operator/Save-Bmw-Collect',
    BMW_FOOTERPROCESS: 'Bmw-Site-Operator/Save-Bmw-Sorting',
    BMW_FOOTERDISTRIBUTE: 'Bmw-Site-Operator/Save-Bmw-Distribute',
    BMWPD_HISTORY: 'Bmw-Site-Operator/Get-Bmw-History?',
    BMWPLASTIC: 'Bmw-Site-Operator/Get-Recyclable-Plastics-Data?',
    BMWGLASS: 'Bmw-Site-Operator/Get-Recyclable-Glass-Data',
    BMWCARDBOARD: 'Bmw-Site-Operator/Get-Recyclable-Cardboard-Data',

    // COLLECT_DASHBOARDBMW: 'bso/bso4/gbc',
    // SORTING_DASHBOARDBMW: 'bso/bso5/gbs',
    // RECYCLABLE_DASHBOARDBMW: 'bso/bso6/gbd',
    // BMW_SUMMARY: 'bso/bso10/gbw',
    // BMW_COLLECTIONTREND: 'bso/bso7/gct',
    // BMW_PROCESSINGTREND: 'bso/bso8/gpt',
    // BMW_RECYCLABLETREND: 'bso/bso9/gdt',
    // BMW_RECYCLABLES: 'Bmw-Site-Operator/Get-Recyclable-Data?',
    // BMW_FOOTERCOLLECT: 'bso/bso1/sbc',
    // BMW_FOOTERPROCESS: 'bso/bso2/sbs',
    // BMW_FOOTERDISTRIBUTE: 'bso/bso3/sbd',
    // BMWPD_HISTORY: 'bso/bso14/gbh',
    // BMWPLASTIC: 'bso/bso11/grpd',
    // BMWGLASS: 'bso/bso12/grgd',
    // BMWCARDBOARD: 'bso/bso13/grcd',
    // ******************** BMW sitehead ****************
    SITE_WASTESUMMARY: 'Bmw-Site-Head/Get-Waste-Summary?',
    SITE_COLLECTIONTREND: 'Bmw-Site-Head/Get-Collection-Trend?',
    SITE_PROCESSINGTREND: 'Bmw-Site-Head/Get-Processing-Trend?',
    SITE_RECYCLABLETREND: 'Bmw-Site-Head/Get-Recyclable-Trend?',
    SITE_WTETREND: 'Bmw-Site-Head/Get-Bmw-Trend?',
    SITE_BMWRECYCLABLE: 'Bmw-Site-Head/Get-Recyclable-Data?',
    BMW_SITE_HISTORY: 'Bmw-Site-Head/Get-Bmw-History?',
    BMW_SITE_HEAD_COLLECTION: 'Bmw-Site-Head/Get-Side-Navbar-Collected-Waste?',
    BMW_SITE_HEAD_PROCESSED: 'Bmw-Site-Head/Get-Side-Navbar-Processed-Waste?',
    BMW_SITE_HEAD_DISTRIBUTE: 'Bmw-Site-Head/Get-Side-Navbar-Distribute-Waste?',
    BMW_PRODUCT_CATALOGUE: 'Bmw-Site-Head/Get-Product-Catalogue?',
    BMW_SITEHEAD_PLASTIC: 'Bmw-Site-Head/Get-Recyclable-Plastics-Data?',
    BMW_SITEHEAD_GLASS: 'Bmw-Site-Head/Get-Recyclable-Glass-Data?',
    BMW_SITEHEAD_CARDBOARD: 'Bmw-Site-Head/Get-Recyclable-Cardboard-Data?',

    // SITE_WASTESUMMARY: 'bsh/bsh1/gws',
    // SITE_COLLECTIONTREND: 'bsh/bsh2/gct',
    // SITE_PROCESSINGTREND: 'bsh/bsh3/gpt',
    // SITE_RECYCLABLETREND: 'bsh/bsh4/grt',
    // SITE_WTETREND: 'bsh/bsh5/gbt',
    // SITE_BMWRECYCLABLE: 'Bmw-Site-Head/Get-Recyclable-Data?',
    // BMW_SITE_HISTORY: 'bsh/bsh9/gbh',
    // BMW_SITE_HEAD_COLLECTION: 'bsh/bsh10/gsncw',
    // BMW_SITE_HEAD_PROCESSED: 'bsh/bsh11/gsnpw',
    // BMW_SITE_HEAD_DISTRIBUTE: 'bsh/bsh12/gsndw',
    // BMW_PRODUCT_CATALOGUE: 'bsh/bsh13/gpc',
    // BMW_SITEHEAD_PLASTIC: 'bsh/bsh6/grpd',
    // BMW_SITEHEAD_GLASS: 'bsh/bsh7/grgd',
    // BMW_SITEHEAD_CARDBOARD: 'bsh/bsh8/grcd',
    // ********************** BMW SABUHEAD ******************
    SBU_WASTESUMAARY: 'Bmw-Business-Head/Get-Waste-Summary?',
    SBU_COLLECTIONTREND: 'Bmw-Business-Head/Get-Collection-Trend?',
    SBU_PROCESSINGTREND: 'Bmw-Business-Head/Get-Processing-Trend?',
    SBU_RECYCLABLETREND: 'Bmw-Business-Head/Get-Recyclable-Trend?',
    SBU_BMWTREND: 'Bmw-Business-Head/Get-Bmw-Trend?',
    SBU_BMWRECYCLABLE: 'Bmw-Business-Head/Get-Recyclable-Data?',
    BMWSBU_HEAD_HISTORY: 'Bmw-Business-Head/Get-Bmw-History?',
    BMW_SBUHEAD_COLLECTION: 'Bmw-Business-Head/Get-Side-Navbar-Collected-Waste?',
    BMW_SBUHEAD_PROCESSING: 'Bmw-Business-Head/Get-Side-Navbar-Processed-Waste?',
    BMW_SBUHEAD_DISTRIBUTE: 'Bmw-Business-Head/Get-Side-Navbar-Distribute-Waste?',
    BMW_SBUHEAD_CATALOGUE: 'Bmw-Business-Head/Get-Product-Catalogue?',
    BMW_SBUHEAD_PLASTIC: 'Bmw-Business-Head/Get-Recyclable-Plastics-Data?',
    BMW_SBUHEAD_GLASS: 'Bmw-Business-Head/Get-Recyclable-Glass-Data?',
    BMW_SBUHEAD_CARDBOARD: 'Bmw-Business-Head/Get-Recyclable-Cardboard-Data?',

    // SBU_WASTESUMAARY: 'bbh/bbh1/gws',
    // SBU_COLLECTIONTREND: 'bbh/bbh2/gct',
    // SBU_PROCESSINGTREND: 'bbh/bbh3/gpt',
    // SBU_RECYCLABLETREND: 'bbh/bbh4/grt',
    // SBU_BMWTREND: 'bbh/bbh5/gbt',
    // SBU_BMWRECYCLABLE: 'Bmw-Business-Head/Get-Recyclable-Data?',
    // BMWSBU_HEAD_HISTORY: 'bbh/bbh9/gbh',
    // BMW_SBUHEAD_COLLECTION: 'bbh/bbh10/gsncw',
    // BMW_SBUHEAD_PROCESSING: 'bbh/bbh11/gsnpw',
    // BMW_SBUHEAD_DISTRIBUTE: 'bbh/bbh12/gsndw',
    // BMW_SBUHEAD_CATALOGUE: 'bbh/bbh13/gpc',
    // BMW_SBUHEAD_PLASTIC: 'bbh/bbh6/grpd',
    // BMW_SBUHEAD_GLASS: 'bbh/bbh7/grgd',
    // BMW_SBUHEAD_CARDBOARD: 'bbh/bbh8/grcd',
    // ********************** IWM Dashboard ******************
    IWM_DASHBOARD_COLLECTION: 'Iwm-Site-Operator/Get-Iwm-Collect?',
    IWM_DASHBOARD_ANALYSIS: 'Iwm-Site-Operator/Get-Iwm-Analysis?',
    IWM_DASHBOARD_LEFTOVERSTOCK: 'Iwm-Site-Operator/Get-Iwm-Leftover-Stock?',
    IWM_SAVE_COLLECT: 'Iwm-Site-Operator/Save-Iwm-Collect',
    IWM_SAVE_ANALYSIS: 'Iwm-Site-Operator/Save-Iwm-Analysis',
    IWM_SAVE_LEFTOVERSTOCK: 'Iwm-Site-Operator/Save-Iwm-Leftover-Stock',
    IWM_COLLECTION_TREND: 'Iwm-Site-Operator/Get-Collection-Trend?',
    IWM_ANALYSIS_TREND: 'Iwm-Site-Operator/Get-Analysis-Trend?',
    IWM_LEFTOVERSTOCK_TREND: 'Iwm-Site-Operator/Get-LeftoverStock-Trend?',
    IWM_SUMMARY: 'Iwm-Site-Operator/Get-Iwm-Summary?',
    IWM_PD_HISTORY: 'Iwm-Site-Operator/Get-Iwm-History?',

    // IWM_DASHBOARD_COLLECTION: 'iso/iso4/gic',
    // IWM_DASHBOARD_ANALYSIS: 'iso/iso5/gia',
    // IWM_DASHBOARD_LEFTOVERSTOCK: 'iso/iso6/gils',
    // IWM_SAVE_COLLECT: 'iso/iso1/sic',
    // IWM_SAVE_ANALYSIS: 'iso/iso2/sia',
    // IWM_SAVE_LEFTOVERSTOCK: 'iso/iso3/sils',
    // IWM_COLLECTION_TREND: 'iso/iso7/gct',
    // IWM_ANALYSIS_TREND: 'iso/iso8/gat',
    // IWM_LEFTOVERSTOCK_TREND: 'iso/iso9/glt',
    // IWM_SUMMARY: 'iso/iso10/gis',
    // IWM_PD_HISTORY: 'iso/iso11/gih',
    // ******************** IWM SITEHEAD *****************
    IWM_WASTE_SUMMARY: 'Iwm-Site-Head/Get-Waste-Summary?',
    IWM_COLECTION_TREND: 'Iwm-Site-Head/Get-Collection-Trend?',
    IWM_ANLYSIS_TREND: 'Iwm-Site-Head/Get-Analysis-Trend?',
    IWM_LEFTOVER_TREND: 'Iwm-Site-Head/Get-LeftoverStock-Trend?',
    IWM_TREND: 'Iwm-Site-Head/Get-Iwm-Trend?',
    IWM_RECYCLABLES_TREND: 'Iwm-Site-Head/Get-Recyclables-Data?',
    IWM_SITE_HISTORY: 'Iwm-Site-Head/Get-Iwm-History?',
    IWM_SITE_COLLECTION: 'Iwm-Site-Head/Get-Side-Navbar-Collected-Waste?',
    IWM_SITE_ANALYSIS: 'Iwm-Site-Head/Get-Side-Navbar-Analysis-Waste?',
    IWM_SITE_LOS: 'Iwm-Site-Head/Get-Side-Navbar-LeftoverStock-Waste?',
    IWM_SITE_HEAD_COLLECTRECYCLABLES: 'Iwm-Site-Head/Get-Recyclables-Collect-Data?',
    IWM_SITE_HEAD_ANALYSISRECYCLABLES: 'Iwm-Site-Head/Get-Recyclables-Analysis-Data?',
    IWM_PRODUCT: "Iwm-Site-Head/Get-Product-Catalogue?",

    // IWM_WASTE_SUMMARY: 'ish/ish1/gws',
    // IWM_COLECTION_TREND: 'ish/ish2/gct',
    // IWM_ANLYSIS_TREND: 'ish/ish3/gat',
    // IWM_LEFTOVER_TREND: 'ish/ish4/glt',
    // IWM_TREND: 'ish/ish5/git',
    // IWM_RECYCLABLES_TREND: 'Iwm-Site-Head/Get-Recyclables-Data?',
    // IWM_SITE_HISTORY: 'ish/ish8/gih',
    // IWM_SITE_COLLECTION: 'ish/ish9/gsncw',
    // IWM_SITE_ANALYSIS: 'ish/ish10/gsnaw',
    // IWM_SITE_LOS: 'ish/ish11/gsnlw',
    // IWM_SITE_HEAD_COLLECTRECYCLABLES: 'ish/ish6/grcd',
    // IWM_SITE_HEAD_ANALYSISRECYCLABLES: 'ish/ish7/grad',
    // IWM_PRODUCT: "ish/ish12/gpc",
    //****************************** IWM SBUHEAD ***********
    IWM_WASTESBU_SUMMARY: 'Iwm-Business-Head/Get-Waste-Summary?',
    IWM_COLLECTIONSBU_TREND: 'Iwm-Business-Head/Get-Collection-Trend?',
    IWM_ANALYSISSBU_TREND: 'Iwm-Business-Head/Get-Analysis-Trend?',
    IWM_LEFTOVERSTOCKSBU_TREND: 'Iwm-Business-Head/Get-LeftoverStock-Trend?',
    IWM_SBU_TREND: 'Iwm-Business-Head/Get-Iwm-Trend?',
    IWM_RECYCLABLESSBU_TREND: 'Iwm-Business-Head/Get-Recyclables-Data?',
    IWM_SBU_HISTORY: 'Iwm-Business-Head/Get-Iwm-History?',
    IWM_SBU_COLLECTION: 'Iwm-Business-Head/Get-Side-Navbar-Collected-Waste?',
    IWM_SBU_ANALYSIS: 'Iwm-Business-Head/Get-Side-Navbar-Analysis-Waste?',
    IWM_SBU_LOS: 'Iwm-Business-Head/Get-Side-Navbar-LeftoverStock-Waste?',
    IWM_SBU_HEAD_COLLECTRECYCLABLES: 'Iwm-Business-Head/Get-Recyclables-Collect-Data?',
    IWM_SBU_HEAD_ANALYSISRECYCLABLES: 'Iwm-Business-Head/Get-Recyclables-Analysis-Data?',
    IWM_SBU_CATALOGUE: "Iwm-Business-Head/Get-Product-Catalogue?",

    // IWM_WASTESBU_SUMMARY: 'ibh/ibh1/gws',
    // IWM_COLLECTIONSBU_TREND: 'ibh/ibh2/gct',
    // IWM_ANALYSISSBU_TREND: 'ibh/ibh3/gat',
    // IWM_LEFTOVERSTOCKSBU_TREND: 'ibh/ibh4/glt',
    // IWM_SBU_TREND: 'ibh/ibh5/git',
    // IWM_RECYCLABLESSBU_TREND: 'Iwm-Business-Head/Get-Recyclables-Data?',
    // IWM_SBU_HISTORY: 'ibh/ibh8/gih',
    // IWM_SBU_COLLECTION: 'ibh/ibh9/gsncw',
    // IWM_SBU_ANALYSIS: 'ibh/ibh10/gsnaw',
    // IWM_SBU_LOS: 'ibh/ibh11/gsnlw',
    // IWM_SBU_HEAD_COLLECTRECYCLABLES: 'ibh/ibh6/grcd',
    // IWM_SBU_HEAD_ANALYSISRECYCLABLES: 'ibh/ibh7/grad',
    // IWM_SBU_CATALOGUE: "ibh/ibh12/gpc",
    // **************************Recycle Plastic PD User API***************************
    RECYCLE_PLASTIC_COLLECTION: 'Recycle-Plastic-Site-Operator/Get-Plastic-Collection',
    RECYCLE_PLASTIC_SEGREGATION: 'Recycle-Plastic-Site-Operator/Get-Plastic-Segregation',
    RECYCLE_PLASTIC_PROCESSED: 'Recycle-Plastic-Site-Operator/Get-Plastic-Processed',
    RECYCLE_PLASTIC_MATERIAL_SUMMARY: 'Recycle-Plastic-Site-Operator/Get-Material-Summary?',
    RECYCLE_PLASTIC_COLLECTION_TREND_GRAPH: 'Recycle-Plastic-Site-Operator/Get-Collected-Trend?',
    RECYCLE_PLASTIC_SEGREGATION_TREND_GRAPH: 'Recycle-Plastic-Site-Operator/Get-Segregated-Trend?',
    RECYCLE_PLASTIC_PROCESSED_TREND_GRAPH: 'Recycle-Plastic-Site-Operator/Get-Processed-Trend?',
    RECYCLE_PLASTIC_SAVE_COLLECTION: 'Recycle-Plastic-Site-Operator/Save-Plastic-Collect',
    RECYCLE_PLASTIC_SAVE_SEGREGATION: 'Recycle-Plastic-Site-Operator/Save-Plastic-Segregation',
    RECYCLE_PLASTIC_SAVE_PROCESSED: 'Recycle-Plastic-Site-Operator/Save-Plastic-Processed',
    RECYCLE_PLASTIC_PROCESSED_SUMMARY: 'Recycle-Plastic-Site-Operator/Get-Processed-Summary?',
    RECYCLE_PLASTIC_PRODUCT_SUMMARY: 'Recycle-Plastic-Site-Operator/Get-Product-Summary?',
    RECYCLE_PLASTIC_HISTORY: 'Recycle-Plastic-Site-Operator/Get-Recycle-Plastic-History?',

    // RECYCLE_PLASTIC_COLLECTION: 'rpso/rpso4/gpc',
    // RECYCLE_PLASTIC_SEGREGATION: 'rpso/rpso5/gps',
    // RECYCLE_PLASTIC_PROCESSED: 'rpso/rpso6/gpp',
    // RECYCLE_PLASTIC_MATERIAL_SUMMARY: 'rpso/rpso10/gms',
    // RECYCLE_PLASTIC_COLLECTION_TREND_GRAPH: 'rpso/rpso7/gct',
    // RECYCLE_PLASTIC_SEGREGATION_TREND_GRAPH: 'rpso/rpso8/gst',
    // RECYCLE_PLASTIC_PROCESSED_TREND_GRAPH: 'rpso/rpso9/gpt',
    // RECYCLE_PLASTIC_SAVE_COLLECTION: 'rpso/rpso1/spc',
    // RECYCLE_PLASTIC_SAVE_SEGREGATION: 'rpso/rpso3/sps',
    // RECYCLE_PLASTIC_SAVE_PROCESSED: 'rpso/rpso2/spp',
    // RECYCLE_PLASTIC_PROCESSED_SUMMARY: 'rpso/rpso11/gps',
    // RECYCLE_PLASTIC_PRODUCT_SUMMARY: 'rpso/rpso12/gpds',
    // RECYCLE_PLASTIC_HISTORY: 'rpso/rpso13/grph',
    // **************************Recycle Plastic Sitehead User API***************************
    RECYCLE_PLASTIC_SITEHEAD_WASTE_SUMMARY: 'Recycle-Plastic-Site-Head/Get-Waste-Summary?',
    RECYCLE_PLASTIC_SITEHEAD_COLLECTED_GRAPH: 'Recycle-Plastic-Site-Head/Get-Collected-Trend?',
    RECYCLE_PLASTIC_SITEHEAD_SEGREGATED_GRAPH: 'Recycle-Plastic-Site-Head/Get-Segregated-Trend?',
    RECYCLE_PLASTIC_SITEHEAD_PROCESSED_GRAPH: 'Recycle-Plastic-Site-Head/Get-Processed-Trend?',
    RECYCLE_PLASTIC_SITEHEAD_PROCESSED_SUMMARY: 'Recycle-Plastic-Site-Head/Get-Processed-Summary?',
    RECYCLE_PLASTIC_SITEHEAD_PRODUCT_SUMMARY: 'Recycle-Plastic-Site-Head/Get-Product-Summary?',
    RECYCLE_PLASTIC_SITEHEAD_HISTORY: 'Recycle-Plastic-Site-Head/Get-Recycle-Plastic-History?',
    RECYCLE_PLASTIC_SITEHEAD_COLLECTED: 'Recycle-Plastic-Site-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_PLASTIC_SITEHEAD_SEGREGATED: 'Recycle-Plastic-Site-Head/Get-Side-Navbar-Segregation-Waste?',
    RECYCLE_PLASTIC_SITEHEAD_PROCESSED: 'Recycle-Plastic-Site-Head/Get-Side-Navbar-Processed-Waste?',

    // RECYCLE_PLASTIC_SITEHEAD_WASTE_SUMMARY: 'rpsh/rpsh1/gws',
    // RECYCLE_PLASTIC_SITEHEAD_COLLECTED_GRAPH: 'rpsh/rpsh2/gct',
    // RECYCLE_PLASTIC_SITEHEAD_SEGREGATED_GRAPH: 'rpsh/rpsh3/gst',
    // RECYCLE_PLASTIC_SITEHEAD_PROCESSED_GRAPH: 'rpsh/rpsh4/gpt',
    // RECYCLE_PLASTIC_SITEHEAD_PROCESSED_SUMMARY: 'rpsh/rpsh5/gps',
    // RECYCLE_PLASTIC_SITEHEAD_PRODUCT_SUMMARY: 'rpsh/rpsh6/gpds',
    // RECYCLE_PLASTIC_SITEHEAD_HISTORY: 'rpsh/rpsh7/grph',
    // RECYCLE_PLASTIC_SITEHEAD_COLLECTED: 'rpsh/rpsh8/gsncw',
    // RECYCLE_PLASTIC_SITEHEAD_SEGREGATED: 'rpsh/rpsh10/gsnsw',
    // RECYCLE_PLASTIC_SITEHEAD_PROCESSED: 'rpsh/rpsh9/gsnpw',
    // ************************** Recycle Plastic business head **************************
    RECYCLE_PLASTIC_BUSINESSHEAD_WASTE_SUMMARY: 'Recycle-Plastic-Business-Head/Get-Waste-Summary?',
    RECYCLE_COLLECTION_GRAPH: 'Recycle-Plastic-Business-Head/Get-Collected-Waste?',
    RECYCLE_SEGREGATION_GRAPH: 'Recycle-Plastic-Business-Head/Get-Segregated-Trend?',
    RECYCLE_PROCESSED_GRAPH: 'Recycle-Plastic-Business-Head/Get-Processed-Trend?',
    RECYCLE_PROCESSED_SUMMARY: 'Recycle-Plastic-Business-Head/Get-Processed-Summary?',
    RECYCLE_PRODUCT_SUMMARY: 'Recycle-Plastic-Business-Head/Get-Product-Summary?',
    RECYCLE_PLASTIC_BUSINESSHEAD_HISTORY: 'Recycle-Plastic-Business-Head/Get-Recycle-Plastic-History?',
    RECYCLE_PLASTIC_BUSINESSHEAD_COLLECTED: 'Recycle-Plastic-Business-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_PLASTIC_BUSINESSHEAD_SEGREGATED: 'Recycle-Plastic-Business-Head/Get-Side-Navbar-Segregation-Waste?',
    RECYCLE_PLASTIC_BUSINESSHEAD_PROCESSED: 'Recycle-Plastic-Business-Head/Get-Side-Navbar-Processed-Waste?',

    // RECYCLE_PLASTIC_BUSINESSHEAD_WASTE_SUMMARY: 'rpbh/rpbh1/gws',
    // RECYCLE_COLLECTION_GRAPH: 'rpbh/rpbh2/gcw',
    // RECYCLE_SEGREGATION_GRAPH: 'rpbh/rpbh3/gst',
    // RECYCLE_PROCESSED_GRAPH: 'rpbh/rpbh4/gpt',
    // RECYCLE_PROCESSED_SUMMARY: 'rpbh/rpbh5/gps',
    // RECYCLE_PRODUCT_SUMMARY: 'rpbh/rpbh6/gpds',
    // RECYCLE_PLASTIC_BUSINESSHEAD_HISTORY: 'rpbh/rpbh7/grph',
    // RECYCLE_PLASTIC_BUSINESSHEAD_COLLECTED: 'rpbh/rpbh8/gsncw',
    // RECYCLE_PLASTIC_BUSINESSHEAD_SEGREGATED: 'rpbh/rpbh10/gsnsw',
    // RECYCLE_PLASTIC_BUSINESSHEAD_PROCESSED: 'rpbh/rpbh9/gsnpw',
    // ******************************** Recycle CND PD User ***********************************
    RECYCLE_CD_SITEOPERATOR_COLLECTED: 'Recycle-CD-Site-Operator/Get-CD-Collect?',
    RECYCLE_CD_SITEOPERATOR_PRODUCT: 'Recycle-CD-Site-Operator/Get-CD-Product?',
    RECYCLE_CD_SITEOPERATOR_PROCESSED: 'Recycle-CD-Site-Operator/Get-CD-Processed?',
    RECYCLE_CD_SITEOPERATOR_SUMMARY: 'Recycle-CD-Site-Operator/Get-Processed-Summary?',
    RECYCLE_CD_SITEOPERATOR_PRODUCT_SUMMARY: 'Recycle-CD-Site-Operator/Get-Product-Summary?',
    RECYCLE_CD_SITEOPERATOR_MATERIAL_SUMMARY: 'Recycle-CD-Site-Operator/Get-Material-Summary?',
    RECYCLE_CD_SITEOPERATOR_COLLECTION_TREND_GRAPH: 'Recycle-CD-Site-Operator/Get-Collected-Trend?',
    RECYCLE_CD_SITEOPERATOR_PROCESSED_TREND_GRAPH: 'Recycle-CD-Site-Operator/Get-Processed-Trend?',
    RECYCLE_CD_SITEOPERATOR_PRODUCT_TREND_GRAPH: 'Recycle-CD-Site-Operator/Get-Product-Trend?',
    RECYCLE_CD_SITEOPERATOR_HISTORY: 'Recycle-CD-Site-Operator/Get-Recycle-CD-History?',
    RECYCLE_CD_SITEOPERATOR_SAVE_COLLECTION: 'Recycle-CD-Site-Operator/Save-CD-Collect',
    RECYCLE_CD_SITEOPERATOR_SAVE_PROCESSED: 'Recycle-CD-Site-Operator/Save-CD-Processed',
    RECYCLE_CD_SITEOPERATOR_SAVE_PRODUCT: 'Recycle-CD-Site-Operator/Save-CD-Product',

    // RECYCLE_CD_SITEOPERATOR_COLLECTED: 'rcso/rsco4/gcc',
    // RECYCLE_CD_SITEOPERATOR_PRODUCT: 'rcso/rsco6/gcpd',
    // RECYCLE_CD_SITEOPERATOR_PROCESSED: 'rcso/rsco5/gcp',
    // RECYCLE_CD_SITEOPERATOR_SUMMARY: 'rcso/rsco11/gps',
    // RECYCLE_CD_SITEOPERATOR_PRODUCT_SUMMARY: 'rcso/rsco12/gpds',
    // RECYCLE_CD_SITEOPERATOR_MATERIAL_SUMMARY: 'rcso/rsco10/gms',
    // RECYCLE_CD_SITEOPERATOR_COLLECTION_TREND_GRAPH: 'rcso/rsco7/gct',
    // RECYCLE_CD_SITEOPERATOR_PROCESSED_TREND_GRAPH: 'rcso/rsco8/gpt',
    // RECYCLE_CD_SITEOPERATOR_PRODUCT_TREND_GRAPH: 'rcso/rsco9/gpdt',
    // RECYCLE_CD_SITEOPERATOR_HISTORY: 'rcso/rsco13/grch',
    // RECYCLE_CD_SITEOPERATOR_SAVE_COLLECTION: 'rcso/rcso1/scc',
    // RECYCLE_CD_SITEOPERATOR_SAVE_PROCESSED: 'rcso/rsco3/scp',
    // RECYCLE_CD_SITEOPERATOR_SAVE_PRODUCT: 'rcso/rsco2/scpd',
    //***************************** CND Site head *********/
    RECYCLE_CD_HEAD_WASTE_SUMMARY: 'Recycle-CD-Site-Head/Get-Waste-Summary?',
    RECYCLE_PRODUCT: "Recycle-CD-Site-Head/Get-Processed-Summary?",
    RECYCLE_CD_SITE_HEAD_PRODUCT_SUMMARY: "Recycle-CD-Site-Head/Get-Product-Summary?",
    RECYCLE_COLECTION_TREND: 'Recycle-CD-Site-Head/Get-Collected-Trend?',
    RECYCLE_PROCESSED_TREND: 'Recycle-CD-Site-Head/Get-Processed-Trend?',
    RECYCLE_PRODUCT_TREND: 'Recycle-CD-Site-Head/Get-Product-Trend?',
    RECYCLE_CD_HEAD_HISTORY: 'Recycle-CD-Site-Head/Get-Recycle-CD-History?',
    RECYCLE_SITE_COLLECTION: 'Recycle-CD-Site-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_SITE_PRODUCT: 'Recycle-CD-Site-Head/Get-Side-Navbar-Product-Waste?',
    RECYCLE_SITE_PROCESSED: 'Recycle-CD-Site-Head/Get-Side-Navbar-Processed-Waste?',

    // RECYCLE_CD_HEAD_WASTE_SUMMARY: 'rcsh/rcsh1/gws',
    // RECYCLE_PRODUCT: "rcsh/rcsh5/gps",
    // RECYCLE_CD_SITE_HEAD_PRODUCT_SUMMARY: "rcsh/rcsh6/gpds",
    // RECYCLE_COLECTION_TREND: 'rcsh/rcsh2/gct',
    // RECYCLE_PROCESSED_TREND: 'rcsh/rcsh3/gpt',
    // RECYCLE_PRODUCT_TREND: 'rcsh/rcsh4/gpdt',
    // RECYCLE_CD_HEAD_HISTORY: 'rcsh/rcsh7/grch',
    // RECYCLE_SITE_COLLECTION: 'rcsh/rcsh8/gsncw',
    // RECYCLE_SITE_PRODUCT: 'rcsh/rcsh10/gsnpw',
    // RECYCLE_SITE_PROCESSED: 'rcsh/rcsh9/gsnpw',
    //************************* CND Business Head  **********/
    RECYCLE_CD_BUSINESS_HEAD_PRODUCT_TREND: 'Recycle-CD-Business-Head/Get-Product-Trend?',
    RECYCLE_CD_BUSINESS_HEAD_PRODUCT_SUMMARY: "Recycle-CD-Business-Head/Get-Product-Summary?",
    RECYCLE_CD_BUSINESS_HEAD_PRODUCT: 'Recycle-CD-Business-Head/Get-Side-Navbar-Product-Waste?',
    RECYCLE_CD_BUSINESS_WASTE_SUMMARY: 'Recycle-CD-Business-Head/Get-Waste-Summary?',
    RECYCLE_CD_COLLECTION_GRAPH: 'Recycle-CD-Business-Head/Get-Collected-Trend?',
    RECYCLE_CD_PROCESSED_GRAPH: 'Recycle-CD-Business-Head/Get-Processed-Trend?',
    RECYCLE_CD_PROCESSED_SUMMARY: 'Recycle-CD-Business-Head/Get-Processed-Summary?',
    RECYCLE_CD_HISTORY: 'Recycle-CD-Business-Head/Get-Recycle-Plastic-History?',
    RECYCLE_CD_NAVBAR_COLLECTED: 'Recycle-CD-Business-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_CD_NAVBAR_PROCESSED: 'Recycle-CD-Business-Head/Get-Side-Navbar-Processed-Waste?',

    // RECYCLE_CD_BUSINESS_HEAD_PRODUCT_TREND: 'rcbh/rcbh4/gpdt',
    // RECYCLE_CD_BUSINESS_HEAD_PRODUCT_SUMMARY: "rcbh/rcbh6/gpds",
    // RECYCLE_CD_BUSINESS_HEAD_PRODUCT: 'rcbh/rcbh10/gsnpdw',
    // RECYCLE_CD_BUSINESS_WASTE_SUMMARY: 'rcbh/rcbh1/gws',
    // RECYCLE_CD_COLLECTION_GRAPH: 'rcbh/rcbh2/gct',
    // RECYCLE_CD_PROCESSED_GRAPH: 'rcbh/rcbh3/gpt',
    // RECYCLE_CD_PROCESSED_SUMMARY: 'rcbh/rcbh5/gps',
    // RECYCLE_CD_HISTORY: 'rcbh/rcbh7/grph',
    // RECYCLE_CD_NAVBAR_COLLECTED: 'rcbh/rcbh8/gsncw',
    // RECYCLE_CD_NAVBAR_PROCESSED: 'rcbh/rcbh9/gsnpw',
    //********************** CRM PD USER *******************/
    RECYCLE_CRM_COLLECT_TABLE: 'Recycle-Crm-Site-Operator/Get-Crm-Collect',
    RECYCLE_CRM_PROCESSED_TABLE: 'Recycle-Crm-Site-Operator/Get-Crm-Processing',
    RECYCLE_CRM_SEGREGATED_TABLE: 'Recycle-Crm-Site-Operator/Get-Crm-Segregate',
    RECYCLE_COLLECT_SAVE: 'Recycle-Crm-Site-Operator/Save-Crm-Collect?',
    RECYCLE_PROCESS_SAVE: 'Recycle-Crm-Site-Operator/Save-Crm-Processed',
    RECYCLE_SEGREGATE_SAVE: 'Recycle-Crm-Site-Operator/Save-Crm-Segregation',
    RECYCLE_COLLECTION_TREND_GRAPH: 'Recycle-Crm-Site-Operator/Get-Collection-Trend?',
    RECYCLE_PROCESSED_TREND_GRAPH: 'Recycle-Crm-Site-Operator/Get-Processing-Trend?',
    RECYCLE_SEGREGATED_TREND_GRAPH: 'Recycle-Crm-Site-Operator/Get-Segregated-Trend?',
    RECYCLE_MATERIAL_SUMMARY: 'Recycle-Crm-Site-Operator/Get-Material-Summary?',
    RECYCLE_CRM_PROCESSED_SUMMARY: 'Recycle-Crm-Site-Operator/Get-Segregated-Summary?',
    RECYCLE_CRM_PRODUCTION_SUMMARY: 'Recycle-Crm-Site-Operator/Get-Production-Summary?',
    RECYCLE_CRM_HISTORY: 'Recycle-Crm-Site-Operator/Get-Recycle-Crm-History?',

    // RECYCLE_CRM_COLLECT_TABLE: 'rcrmso/rcrmso4/gcc',
    // RECYCLE_CRM_PROCESSED_TABLE: 'rcrmso/rcrmso5/gcp',
    // RECYCLE_CRM_SEGREGATED_TABLE: 'rcrmso/rcrmso6/gcs',
    // RECYCLE_COLLECT_SAVE: 'rcrmso/rcrmso1/scc',
    // RECYCLE_PROCESS_SAVE: 'rcrmso/rcrmso2/scp',
    // RECYCLE_SEGREGATE_SAVE: 'rcrmso/rcrmso3/scs',
    // RECYCLE_COLLECTION_TREND_GRAPH: 'rcrmso/rcrmso7/gct',
    // RECYCLE_PROCESSED_TREND_GRAPH: 'rcrmso/rcrmso8/gpt',
    // RECYCLE_SEGREGATED_TREND_GRAPH: 'rcrmso/rcrmso9/gst',
    // RECYCLE_MATERIAL_SUMMARY: 'rcrmso/rcrmso10/gms',
    // RECYCLE_CRM_PROCESSED_SUMMARY: 'rcrmso/rcrmso11/gss',
    // RECYCLE_CRM_PRODUCTION_SUMMARY: 'rcrmso/rcrmso12/gps',
    // RECYCLE_CRM_HISTORY: 'rcrmso/rcrmso13/grch',
    //****************** CRM SITEHEAD *******************/
    RECYCLE_CRM_SITE_COLLECTION_TREND_GRAPH: 'Recycle-Crm-Site-Head/Get-Collection-Trend?',
    RECYCLE_CRM_SITE_PROCESSED_TREND_GRAPH: 'Recycle-Crm-Site-Head/Get-Processing-Trend?',
    RECYCLE_CRM_SITE_MATERIAL_SUMMARY: 'Recycle-Crm-Site-Head/Get-Material-Summary?',
    RECYCLE_CRM_SITE_PROCESSED_SUMMARY: 'Recycle-Crm-Site-Head/Get-Segregated-Summary?',
    RECYCLE_CRM_SITE_PRODUCTION_SUMMARY: 'Recycle-Crm-Site-Head/Get-Production-Summary?',
    RECYCLE_CRM_SITE_SEGREGATED_TREND_GRAPH: 'Recycle-Crm-Site-Head/Get-Segregated-Trend?',
    RECYCLE_CRM_SITE_HISTORY: 'Recycle-Crm-Site-Head/Get-Recycle-Crm-History?',
    RECYCLE_CRM_SITE_NAVBAR_COLLECTED: 'Recycle-Crm-Site-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_CRM_SITE_NAVBAR_PROCESSED: 'Recycle-Crm-Site-Head/Get-Side-Navbar-Processed-Waste?',
    RECYCLE_CRM_SITE_NAVBAR_SEGREGATED: 'Recycle-Crm-Site-Head/Get-Side-Navbar-Segregated-Waste?',

    // RECYCLE_CRM_SITE_COLLECTION_TREND_GRAPH: 'rcrmsh/rcrmsh1/gct',
    // RECYCLE_CRM_SITE_PROCESSED_TREND_GRAPH: 'rcrmsh/rcrmsh2/gpt',
    // RECYCLE_CRM_SITE_MATERIAL_SUMMARY: 'rcrmsh/rcrmsh4/gms',
    // RECYCLE_CRM_SITE_PROCESSED_SUMMARY: 'rcrmsh/rcrmsh5/gss',
    // RECYCLE_CRM_SITE_PRODUCTION_SUMMARY: 'rcrmsh/rcrmsh6/gps',
    // RECYCLE_CRM_SITE_SEGREGATED_TREND_GRAPH: 'rcrmsh/rcrmsh3/gst',
    // RECYCLE_CRM_SITE_HISTORY: 'rcrmsh/rcrmsh7/grch',
    // RECYCLE_CRM_SITE_NAVBAR_COLLECTED: 'rcrmsh/rcrmsh8/gsncw',
    // RECYCLE_CRM_SITE_NAVBAR_PROCESSED: 'rcrmsh/rcrmsh10/gsnpw',
    // RECYCLE_CRM_SITE_NAVBAR_SEGREGATED: 'rcrmsh/rcrmsh9/gsnsw',
    //************************ CRM BUSINESS HEAD  ********************/
    RECYCLE_CRM_BUSINESS_COLLECTION_TREND_GRAPH: 'Recycle-Crm-Buisness-Head/Get-Collection-Trend?',
    RECYCLE_CRM_BUSINESS_PROCESSED_TREND_GRAPH: 'Recycle-Crm-Buisness-Head/Get-Processed-Trend?',
    RECYCLE_CRM_BUSINESS_MATERIAL_SUMMARY: 'Recycle-Crm-Buisness-Head/Get-Material-Summary?',
    RECYCLE_CRM_BUSINESS_PROCESSED_SUMMARY: 'Recycle-Crm-Buisness-Head/Get-Segregated-Summary?',
    RECYCLE_CRM_BUSINESS_PRODUCTION_SUMMARY: 'Recycle-Crm-Buisness-Head/Get-Product-Summary?',
    RECYCLE_CRM_BUSINESS_SEGREGATED_TREND_GRAPH: 'Recycle-Crm-Buisness-Head/Get-Segregated-Trend?',
    RECYCLE_CRM_BUSINESS_HISTORY: 'Recycle-Crm-Buisness-Head/Get-Recycle-Crm-History?',
    RECYCLE_CRM_BUSINESS_NAVBAR_COLLECTED: 'Recycle-Crm-Buisness-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_CRM_BUSINESS_NAVBAR_PROCESSED: 'Recycle-Crm-Buisness-Head/Get-Side-Navbar-Processed-Waste?',
    RECYCLE_CRM_BUSINESS_NAVBAR_SEGREGATED: 'Recycle-Crm-Buisness-Head/Get-Side-Navbar-Segregated-Waste?',

    // RECYCLE_CRM_BUSINESS_COLLECTION_TREND_GRAPH: 'rcrmbh/rcrmbh1/gct',
    // RECYCLE_CRM_BUSINESS_PROCESSED_TREND_GRAPH: 'rcrmbh/rcrmbh2/gpt',
    // RECYCLE_CRM_BUSINESS_MATERIAL_SUMMARY: 'rcrmbh/rcrmbh4/gms',
    // RECYCLE_CRM_BUSINESS_PROCESSED_SUMMARY: 'rcrmbh/rcrmbh5/gss',
    // RECYCLE_CRM_BUSINESS_PRODUCTION_SUMMARY: 'rcrmbh/rcrmbh6/gps',
    // RECYCLE_CRM_BUSINESS_SEGREGATED_TREND_GRAPH: 'rcrmbh/rcrmbh3/gst',
    // RECYCLE_CRM_BUSINESS_HISTORY: 'rcrmbh/rcrmbh7/grch',
    // RECYCLE_CRM_BUSINESS_NAVBAR_COLLECTED: 'rcrmbh/rcrmbh8/gsncw',
    // RECYCLE_CRM_BUSINESS_NAVBAR_PROCESSED: 'rcrmbh/rcrmbh10/gsnpw',
    // RECYCLE_CRM_BUSINESS_NAVBAR_SEGREGATED: 'rcrmbh/rcrmbh9/gsnsw',
    // ****************************** SBU HEAD RECYCLE *******************/
    RECYCLE_SBUHEAD_GET_SITENAME: 'Recycle-SBU-Head/Get-SiteName-By-Department?',
    RECYCLE_SBUHEAD_WASTE_SUMMARY: 'Recycle-SBU-Head/Get-Waste-Summary?',
    RECYCLE_SBUHEAD_CND_HISTORY: 'Recycle-SBU-Head/Get-Recycle-CND-History?',
    RECYCLE_SBUHEAD_PLASTIC_HISTORY: 'Recycle-SBU-Head/Get-Recycle-Plastic-History?',
    RECYCLE_SBUHEAD_PROCESSED_SUMMARY: 'Recycle-SBU-Head/Get-Processed-Summary?',
    RECYCLE_SBUHEAD_PRODUCT_SUMMARY: 'Recycle-SBU-Head/Get-Product-Summary?',
    RECYCLE_SBUHEAD_CRM_HISTORY: 'Recycle-SBU-Head/Get-Recycle-Crm-History?',
    RECYCLE_SBU_HEAD_COLLECTION_TREND: 'Recycle-SBU-Head/Get-Collected-Trend?',
    RECYCLE_SBU_HEAD_PROCESSED_TREND: 'Recycle-SBU-Head/Get-Processed-Trend?',
    RECYCLE_SBU_HEAD_SEGREGATED_TREND: 'Recycle-SBU-Head/Get-Segregated-Trend?',
    RECYCLE_SBU_HEAD_SIDENAVE_PLASTICCOLLECT_WASTE:'Recycle-SBU-Head/Get-Side-Navbar-Collected-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_PLASTICPROCESSED_WASTE:'Recycle-SBU-Head/Get-Side-Navbar-Processed-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_PLASTICSEGREGATED_WASTE:'Recycle-SBU-Head/Get-Side-Navbar-Segregation-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CND_COLLECT_WASTE:'Recycle-SBU-Head/Get-CND-Side-Navbar-Collected-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CNDPROCESSED_WASTE:'Recycle-SBU-Head/Get-CND-Side-Navbar-Processed-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CNDSEGREGATED_WASTE:'Recycle-SBU-Head/Get-CND-Side-Navbar-Product-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CRM_COLLECT_WASTE:'Recycle-SBU-Head/Get-CRM-Side-Navbar-Collected-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CRMPROCESSED_WASTE:'Recycle-SBU-Head/Get-CRM--Side-Navbar-Processed-Waste?',
    RECYCLE_SBU_HEAD_SIDENAVE_CRMSEGREGATED_WASTE:'Recycle-SBU-Head/Get-CRM-Side-Navbar-Segregated-Waste?', 
    RECYCLE_SBU_HEAD_SEGREGATED_SUMMARY:'Recycle-SBU-Head/Get-Segregated-Summary?',
    RECYCLE_SBU_HEAD_PRODUCT_TREND:'Recycle-SBU-Head/Get-Product-Trend?',

    // RECYCLE_SBUHEAD_GET_SITENAME: 'rsh/rsh1/gsbd',
    // RECYCLE_SBUHEAD_WASTE_SUMMARY: 'rsh/rsh2/gws',
    // RECYCLE_SBUHEAD_CND_HISTORY: 'rsh/rsh6/grcndh',
    // RECYCLE_SBUHEAD_PLASTIC_HISTORY: 'rsh/rsh5/grph',
    // RECYCLE_SBUHEAD_PROCESSED_SUMMARY: 'rsh/rsh3/gprs',
    // RECYCLE_SBUHEAD_PRODUCT_SUMMARY: 'rsh/rsh4/gpds',
    // RECYCLE_SBUHEAD_CRM_HISTORY: 'rsh/rsh7/grcrmh',
    // RECYCLE_SBU_HEAD_COLLECTION_TREND: 'rsh/rsh8/gct',
    // RECYCLE_SBU_HEAD_PROCESSED_TREND: 'rsh/rsh9/gprt',
    // RECYCLE_SBU_HEAD_SEGREGATED_TREND: 'rsh/rsh10/gst',
    // RECYCLE_SBU_HEAD_SIDENAVE_PLASTICCOLLECT_WASTE:'rsh/rsh11/gpsncw',
    // RECYCLE_SBU_HEAD_SIDENAVE_PLASTICPROCESSED_WASTE:'rsh/rsh12/gpsnpw',
    // RECYCLE_SBU_HEAD_SIDENAVE_PLASTICSEGREGATED_WASTE:'rsh/rsh13/gpsnsw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CND_COLLECT_WASTE:'rsh/rsh14/gcndncw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CNDPROCESSED_WASTE:'rsh/rsh15/gcndsnpw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CNDSEGREGATED_WASTE:'rsh/rsh16/gcndsnpdw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CRM_COLLECT_WASTE:'rsh/rsh17/gcrmsncw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CRMPROCESSED_WASTE:'rsh/rsh19/gcrmsnpw',
    // RECYCLE_SBU_HEAD_SIDENAVE_CRMSEGREGATED_WASTE:'rsh/rsh18/gcrmsnsw', 
    // RECYCLE_SBU_HEAD_SEGREGATED_SUMMARY:'rsh/rsh20/gss',
    // RECYCLE_SBU_HEAD_PRODUCT_TREND:'rsh/rsh21/gpdt',
};
const STATIC_PAGE = {
    PRIVACY_POLICY: '',
    TERMS_CONDITION: '',
};
//================== Font Family ===============================//
const FONT_FAMILIES = {
    MONTSERAT_ITALIC: 'Montserrat-Italic',
    MONTSERAT_BLACK: 'Montserrat-Black',
    MONTSERAT_BOLD: 'Montserrat-Bold',
    MONTSERAT_LIGHT: 'Montserrat-Light',
    MONTSERAT_MEDIUM: 'Montserrat-Medium',
    MONTSERAT_REGULAR: 'Montserrat-Regular',
    MONTSERAT_SEMIBOLD: 'Montserrat-SemiBold',
    MONTSERAT_THIN: 'Montserrat-Thin',
    AVERTA_THIN: 'AvertaStd-Thin',
    AVERTA_BLACK: 'AvertaStd-Black',
    AVERTA_BOLD: 'AvertaStd-Bold',
    AVERTA_LIGHT: 'AvertaStd-Light',
    AVERTA_REGULAR: 'AvertaStd-Regular',
};
//================ MARGIN and PADDINGS ===================//
const METRICS = {
    MAR_5: 5,
    MAR_8: 8,
    MAR_9: 9,
    MAR_10: 10,
    MAR_11: 11,
    MAR_12: 12,
    MAR_13: 13,
    MAR_14: 14,
    MAR_15: 15,
    MAR_16: 16,
    MAR_17: 17,
    MAR_18: 18,
    MAR_19: 19,
    MAR_20: 20,
    MAR_21: 21,
    MAR_22: 22,
    MAR_23: 23,
    MAR_24: 24,
    MAR_25: 25,
    MAR_29: 29,
    MAR_30: 30,
    MAR_32: 32,
    MAR_35: 35,
    MAR_40: 40,
    MAR_45: 45,
    MAR_50: 50,
    MAR_55: 55,
    MAR_60: 60,
    MAR_66: 66,
    MAR_81: 81,
    MAR_104: 104,
    MAR_110: 110,
    MAR_120: 120,
    MAR_131: 131,
};
//==================== Define Colors ========================//
const COLORS = {
    GRAY_BACKGROUND: 'rgba(190,190,190,0.5)',
    GRAY: 'gray',
    BORDER_COLOR: 'gray',
    WHITE: '#FFFFFF',
    BLACK: 'black',
    RED: 'red',
    GREEN: 'green',
    GRAY_255_6: 'rgba(255,255,255,0.6)',
    GOLD: '#E6C65B',
    GREEN1: " #E41F25",
    PRIMARY_LIGHT: "#FFF0F1",
    NAME: '#000000',
    TEXTINPUT: '#333333',
    LIGHT_GRAY: '#333333',
    TEXT_INPUT1: "#EEEEEE",
};
//========================= FONT SIZE =========================//
const FONT_SIZES = {
    H1: 24,
    H2: 16,
    H3: 14,
    H4: 12,
    H5: 18,
    H6: 20,
};
export {
    HTTP_CODES,
    FONT_FAMILIES,
    FONT_SIZES,
    URIS,
    COLORS,
    METRICS,
    // eslint-disable-next-line camelcase
    URI_METHODs,
    STATIC_PAGE,
};