//======================= Screen Names ===================//
const SCREENS = {
    MAIN1: 'main1',
    MAIN2: 'main2',
    MAIN3: 'main3',
    MAIN4: 'main4',
    MAIN5: 'main5',
    MAIN6: 'main6',
    MAIN7: 'main7',
    MAIN8: 'main8',
    MAIN9: 'main9',
    MAIN10: 'main10',
    MAIN11: 'main11',
    MAIN0: 'main0',
    MAIN12: 'main12',
    MAIN13: 'main13',
    MAIN14: 'main14',
    MAIN15: 'main15',
    MAIN16: 'main16',
    MAIN17: 'main17',
    MAIN18: 'main18',
    MAIN20: 'main20',
    MAIN21: 'main21',
    MAIN22: 'main22',
    TABS: 'tabs',
    HISTORY: 'history',
    SPLASH: 'splash',
    LOGIN: 'login',
    FORGET_PASSWORD: 'forget password',
    RESET_PASSWORD: 'reset password',
    REGISTER: 'register',
    PRIVACY_POLICY: 'privacy policy',
    DASHBOARD: 'dashboard',
    DISTRIBUTE: 'distribute',
    DASHBOARDWTE: 'dashboardwte',
    DASHBOAD_SITE: 'dashboardsite',
    DASHBOARD_BUSINESS: 'dashboardbusiness',
    FORGOT_NUMBER: 'forgot number',
    OTP_VERIFY: 'otp verify',
    CONFIRM_PASSWORD: 'confirm password',
    HISTORYY: 'history',
    HELPCENETER: 'HelpCenter',
    ACCOUNTINFO: 'AccountInfo',
    CHANGEPASS: 'ChangePass',
    NOTIFICATION: 'Notification',
    BMWOPERATIONUSER: 'operationbmw',
    BMWBUSINESSHEAD: 'businessbmw',
    BMWSITEHEAD: 'siteheadbmw',
    IMWOPERATIONUSER: 'Operationiwm',
    IWMOPERATIONSITE: 'operationsiteiwm',
    IWMBUSINESSHEAD: 'operationsbuhead',
    RECYCLEPLASTICUSER: 'plasticuser',
    RECYCLEPLASTICSITEUSER: 'plasticsiteuser',
    RECYCLEPLASTICSBUHEADUSER: 'plasticbusinessuser',
    RECYCLEPLASTICBUSINESSHEAD: 'plasticbusinesshead',
    RECYCLECDUSER: 'recyclecduser',
    RECYCLECDSITEUSER: 'recyclecdsiteuser',
    RECYCLECDBUSINESSHEAD: 'recyclebusinesshead',
    RECYCLECRMCD: 'recyclecrmcd',
    RECYCLECRMSITEHEAD: 'recyclecrmsitehead',
    RECYCLECRMBUSINESSHEAD: 'recyclecrmbusinesshead',
};
//==================== Validation Messages =================//
const VALIDATE_FORM = {
    FIRST_NAME: 'Please enter first name.',
    LAST_NAME: 'Please enter last name.',
    EMAIL: 'Please enter email address.',
    EMAIL_VALID: 'Please enter valid email address.',
    PASSWORD: 'Please enter password.',
    PASSWORD_LENGTH: 'PLease Enter More than 8 Character password',
    VALID_PASSWORD: 'Please use atleast a number and the uppercase character and also the special character',
    VALID_PHONE: 'Please enter valid mobile number.',
    DOB: 'Please enter DOB.',
    SCREEN_NAME: 'Please enter screen name',
    NEW_PASSWORD: 'please enter new password',
    C_PASSWORD: 'Please enter confirm password.',
    MISMATCH: "Password doesn't match",
    LOGOUT: 'Are you sure you want to logout?',
    PRIVACY: 'Please select post privacy.',
    ADDRESS: 'Please enter location',
    GENDER: 'Please select gender.',
    PHONE: 'Please enter phone number',
    TERMS_AND_CODITION: 'Please Accept Terms & Conditions and Privacy Policy.',
    OTP: 'Please Enter Otp',
    OTP_LENGTH: 'Please Enter Valid Otp',
    WASTE: 'Please Enter Waste',
    WEIGHT: 'Please Ener Weight',
    // ************************************MSW CT User Validation Message******************************************
    MSWCTQUANTITY: 'Please Enter Quantity',
    MSWCTCOMMENT: 'Please Enter Comments',
    // ************************************MSW PD User Validation Message******************************************
    TOTALWASTE: 'Please Enter Total Waste',
    TOTALRDF: 'Please Enter Total RDF',
    TOTALINERTS: 'Please Enter Total Inerts',
    TOTALCOMPOST: 'Please Enter Total Compost',
    TOTALRECYCLABLE: 'Please Enter Total Recyclables',
    PROCESSINGCOMMENT: 'Please Enter Comments',
    // ************************************MSW Distribute User Validation Message******************************************
    COMPOSTVENDORNAME: 'Please Enter Compost Vendor Name',
    COMPOSTQUANTITY: 'Please Enter Compost',
    RDFVENDORNAME: 'Please Enter RDF Vendor Name',
    RDFQUANTITY: 'Please Enter RDF',
    RECYCLABLEVENDORNAME: 'Please Enter Recyclable Vendor Name',
    RECYCLABLEQUANTITY: 'Please Enter Recyclable',
    INERTSVENDORNAME: 'Please Enter Inerts Vendor Name',
    INERTSQUANTITY: 'Please Enter Inerts',
    DISTRIBUTECOMMENT: 'Please Enter Comments',
    // ***********************************MSW WTE User Validation Message******************************************
    WTERECEIPT: 'Please Enter RDF Receipt',
    WTECOMBUSTED: 'Please Enter RDF Combusted',
    WTEASH: 'Please Enter Ash Generated',
    STEAM: 'Please Enter Steam Generation',
    PRODUCED: 'Please Enter Power Produced',
    EXPORT: 'Please Enter Power Export',
    WTECOMMENT: 'Please Enter Comments',
    // ***************** BMW PROCESSING VALIDATION****************
    PROCESSINGTOTALWASTE:'Please Enter Total Waste',
    PROCESSINGINCINERATION:'Please Enter Incineration',
    PROCESSINGAUTOCLAVE:'Please Enter Autoclave',
     // ****************** BMW Distribute Validation Message*******************
     BMWDISTRIBUTETOTALMATERIAL: 'Please Enter Total Material',
     BMWDISTRIBUTERECYCLABLES: 'Please Enter Recyclables',
     BMWDISTRIBUTEPLASTICS: 'Please Enter Plastics',
     BMWDISTRIBUTEBAGS: 'Please Enter Bags',
     BMWDISTRIBUTEGLASS: 'Please Enter Glass',
     BMWDISTRIBUTECATRDBOARD: 'Please Enter Cardboard',
     BMWDISTRIBUTECOMMENT: 'Please Enter Comments',
// ************************************Recycle CRM PD User Validation Message******************************************
     CRMPDQUANTITY: 'Please Enter Total Quantity',
     CRMPDCOMMENT: 'Please Enter Comments',
     // ****************** Recycle Plastic Collect User validation**********************
    PLASTICCOLLECTTOTALWEIGHT: 'Please Enter Total Weight',
    PLASTICCOLLECTCOMMENT: 'Please Enter Comments',
    // ****************** Recycle Plastic Segregation User validation**********************
    PLASTICSEGREGATIONHDPE: 'Please Enter HDPE Waste',
    PLASTICSEGREGATIONLDPE: 'Please Enter LDPE Waste',
    PLASTICSEGREGATIONPET: 'Please Enter PET Waste',
    PLASTICSEGREGATIONPP: 'Please Enter PP Waste',
    PLASTICSEGREGATIONOTHER: 'Please Enter Others Waste',
    PLASTICSEGREGATIONCOMMENT: 'Please Enter Comments',
    // ****************** Recycle Plastic Processed User validation**********************
    PLASTICPROCESSEDTOTALWASTE: 'Please Enter Total Waste',
    PLASTICPROCESSEDREGRINDS: 'Please Enter Regrinds',
    PLASTICPROCESSEDGRANULES: 'Please Enter Granules',
    PLASTICPROCESSEDBAGS: 'Please Enter Bags',
    PLASTICPROCESSEDBALES: 'Please Enter Bales',
    PLASTICPROCESSEDCOMMENT: 'Please Enter Comments',
      // ************************************Recycle CRM PD User Validation Message******************************************
//***********Segergated */
TOTALSCRAP:'Please Enter Total Scrap',
SEGTOTALPLASTIC:'Please Enter Total Plastic',
SEGHDPE:'Please Enter HDPE Plastic',
SEGLDPE:'Please Enter LDPE Plastic',
SEGPP:'Please Enter PP Plastic',
SEGPET:'Please Enter PET Plastic',
SEGOTHERPLASTIC:'Please Enter Others Plastic',
SEGTOTALPAPER:'Please Enter Total Paper',
SEGCARDBOARD:'Please Enter Card Board',
SEGMIXEDPAPAER:'Please Enter Mixed Paper',
SEGONP:'Please Enter ONP',
SEGTOTALMETAL:'Please Enter Total Metal',
SEGTOTALGLASS:'Please Enter Total Glass',
SEGWOOD:'Please Enter Others Product',
//********PROCESSED */
PROCESSEDPET:'Please Enter PET ',
PROCESSEDHDPE:'Please Enter HDPE ',
PROCESSEDLDPE:'Please Enter LDPE ',
PROCESSEDPP:'Please Enter PP',
PROCESSEDOTHER:'Please Enter Others',
// ************************************Recycle CD PD PROCESSED User Validation Message**********************
RECYCLECDPROCESSEDFINE: 'Please Enter Fine',
RECYCLECDPROCESSEDCOARSES: 'Please Enter Coarse s',
RECYCLECDPROCESSED10MM: 'Please Enter 10 mm',
RECYCLECDPROCESSED20MM: 'Please Enter 20 mm',
RECYCLECDPROCESSEDVSAND: 'Please Enter V Sand',
RECYCLECDPROCESSEDGSB: 'Please Enter GSB',
RECYCLECDPROCESSEDOTHERS: 'Please Enter Others',
// ************************************Recycle CD PD PRODUCT User Validation Message**********************
RECYCLECDPRODUCTKREBS: 'Please Enter Krebs Stones',
RECYCLECDPRODUCTPAVER: 'Please Enter Paver Blocks',
RECYCLECDPRODUCTCEMENT: 'Please Enter Cement Bricks',
RECYCLECDPRODUCTOTHERS: 'Please Enter Others Product',
// **************************** IWM Disposal ******************************
IWMTOTALWASTE:'Please Enter Total Waste',
IWMDLF:'Please Enter DLF',
IWMLAT:'Please Enter LAT',
IWMINCINERATION:'Please Enter Incineration',
IWMAFRF:'Please Enter AFRF',
};
const Credentials = {
    // eslint-disable-next-line camelcase
    Pass_key: "ckZRT4ZWQvTJBByChc4ANYnY655GLvPzrs2akSH2XsmqSJCZxxbampLgjFPF2e5ggG3tqA5cS2dmmFcH3duet5mnBLSdCy6J5YM6at8SjW5vuSNmG8rKNpWZKE4XNLjJ",
};
export {
    SCREENS,
    VALIDATE_FORM,
    Credentials,
};