//================= Images files add here =============//
const Images = {
  splash: require("./Splash/splash.png"),
  back: require("./back/back.png"),
  menu: require("./menu/menu.png"),
  notification: require("./notification/notification.png"),
  dummy: require("./user/dummy.png"),
  home1: require("./menu/home1.png"),
  logout: require("./menu/logout.png"),
  setting: require("./menu/setting.png"),
  user: require("./menu/user.png"),
  home: require("./tab/home.png"),
  clock: require("./tab/clock.png"),
  backlogin: require("./user/backlogin.png"),
  email: require("./user/email.png"),
  lock: require("./user/lock.png"),
  eye: require("./user/eye.png"),
  collect: require("./user/collect.png"),
  sorting: require("./user/sorting.png"),
  distribute: require("./user/distribute.png"),
  drawer: require("./user/drawer.png"),
  man: require("./user/man.png"),
  back1: require("./user/back1.png"),
  search: require("./user/Search.png"),
  location: require("./user/location.png"),
  energy: require("../Assets/user/Energy.png"),
  circle: require("../Assets/tab/circle.png"),
  forward: require("../Assets/tab/forward.png"),
  eye1: require("./tab/eye.png"),
  share: require("./tab/share.png"),
  download: require("./tab/download.png"),
  backarrow: require("./tab/backarrow.png"),
  bargraph: require("./tab/bargraph.png"),
  dropdown: require("./back/upward.png"),
  dropdown2: require("./tab/Path.png"),
  calendar: require("./user/calendar.png"),
  calender1: require("./user/calender1.png"),
  checked: require("./user/checked.png"),
  uncheck: require("./user/uncheck.png"),
  closebar: require("./user/closebar.png"),
  Call: require("./user/Call.png"),
  Camera: require("./user/Camera.png"),
  rightArrow: require("./user/rightArrow.png"),
  Upword: require('./back/Path.png'),
  notification1: require("./tab/notification.png"),
  circle2: require("./tab/circle2.png"),
  Compost: require("./user/Compost.png"),
  RDF: require("./user/RDF.png"),
  Recyclables: require("./user/Recyclables.png"),
  Inerts: require("./user/Inerts.png"),
  Close: require('./user/close.png'),
  Trash: require('./user/trash.png'),
  vector: require('./back/Vector.png'),
  Greater: require('./back/greater.png'),
  Defaultdp: require('./user/default.png'),
  footerDropdown: require('./back/Path.png'),
  Splash2: require('./Splash/Splash2.png'),
  Hdpe: require('./user/Hdpe.png'),
  Ldpe: require('./user/Ldpe.png'),
  Pet: require('./user/Pet.png'),
  Pp: require('./user/Pp.png'),
  Other: require('./user/Others.png'),
  Plastics:require('./user/Plastics.png'),
  Paper:require('./user/Paper.png'),
  Metal:require('./user/Metal.png'),
  Glass:require('./user/Glass.png'),
  Wood:require('./user/Wood.png'),
  arrow1:require('./user/arrows.png'),
  arrow2:require('./user/arrows2.png'),
  arrow3:require('./user/arrows3.png')
};
export { Images };
